server:
  port: 8080 # 충돌 문제 시 수정
spring:
  # JPA
  jpa:
    hibernate:
      # ddl-auto: create # 배포 시는 none 또는 validate 추천
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL
        # dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL
        show_sql: true
        format_sql: true
  # 데이터소스
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL
    # driver-class-name: org.postgresql.Driver # PostgreSQL
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 객체 스토리지
  supabase:
    url: ${SUPABASE_URL}
    access-key: ${SUPABASE_ACCESS_KEY}
    pdf-bucket-name: ${SUPABASE_PDF_BUCKET_NAME}
    sheet-bucket-name: ${SUPABASE_SHEET_BUCKET_NAME}
    img-bucket-name: ${SUPABASE_IMG_BUCKET_NAME}

  # Security
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - profile_nickname
#        #              - account_email # 추가적 동의가 필요하다
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

# JWT
jwt:
  # openssl rand -base64 32
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS} # 1시간

# Swagger
# 여러 가지 설정 on-off 및 dev, prod 분기
springdoc:
  swagger-ui:
  # enabled: true # 개발 환경에선
  enabled: false # 배포 환경에선
  api-docs:
  # enabled: true # 개발 환경에선
  enabled: false # 배포 환경에선

# 화면단 url
#front-end:
#  redirect: ${FRONT_END_REDIRECT}