server:
  port: 8080
spring:
  application:
    name: reboot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # JPA가 테이블 구조를 변경하지 않도록 설정
    defer-datasource-initialization: true  # SQL 스크립트가 JPA 이후에 실행되도록
    show-sql: false   # 운영 환경에서는 false로 설정하여 로그 최소화
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false  # 운영 환경에서는 false로 설정
  sql:
    init:
      mode: never

  # 파일 업로드 설정 추가
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

  supabase:
    url: ${SUPABASE_URL}
    access-key: ${SUPABASE_ACCESS_KEY}
    img-bucket-name: ${SUPABASE_IMG_BUCKET_NAME}

together:
  ai:
    api:
      key: ${TOGETHER_AI_API_KEY}
      url: ${TOGETHER_AI_API_URL}
    model: ${TOGETHER_AI_MODEL}

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:86400000}

# Swagger - 운영 환경에서는 비활성화
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.reboot