spring:
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql
        data-locations: classpath:data.sql